apps/web/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .forms import UserPasswordResetForm
from .views import (
    login_view,
    register_view,
    logout_view,
    CustomPasswordChangeView,
    ProfileView,
    ProfileEditView,
)

urlpatterns = [
    path('login-view/', login_view, name='login'),
    path('register-user/', register_view, name='register'),
    path('logout-user/', logout_view, name='logout'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset/password_reset.html',
             form_class=UserPasswordResetForm,
         ),
         name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    path('change-user-password/', CustomPasswordChangeView.as_view(), name='change_password'),

    path('profile-user-view/<str:user>/', ProfileView.as_view(), name='profile'),

    path('edit-profile/', ProfileEditView.as_view(), name='profile_edit'),
]

apps/web/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import (
    handler404
)

admin_url = settings.ADMIN_URL

urlpatterns = [
    path(admin_url, admin.site.urls),
    path('chat/', include('chat.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),
]

handler404 = 'pages.views.error_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/web/apps/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save

# Create your models here.

User = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_image = models.ImageField(upload_to='profile_images/', null=True, blank=True)
    user_banner = models.ImageField(upload_to='banner_images/', null=True, blank=True)
    bio = models.TextField(default='Hello there! I am using Chat', max_length=225)
    instagram_url = models.URLField(null=True, blank=True)
    linkedin_url = models.URLField(null=True, blank=True)
    github_url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.user.username

apps/web/apps/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm, PasswordChangeForm

from .models import Profile

User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(min_length=6, max_length=20,
                               widget=forms.TextInput(attrs={
                                   'class': 'bg-gray-200 border-2 border-gray-100 focus:outline-none bg-gray-100 block w-full py-2 px-4 rounded-lg focus:border-gray-700',
                                   'placeholder': 'Enter your Username...',
                                   'label': ''
                               }))
    password = forms.CharField(min_length=8, max_length=20,
                               widget=forms.PasswordInput(attrs={
                                   'class': 'bg-gray-200 border-2 border-gray-100 focus:outline-none bg-gray-100 block w-full py-2 px-4 rounded-lg focus:border-gray-700',
                                   'placeholder': 'Enter your Password...',
                                   'label': '',
                               }))

    def clean_username(self, *args, **kwargs):
        username_form = self.cleaned_data.get('username')
        obj = User.objects.filter(username__iexact=username_form)
        if not obj.exists():
            information = "The Username does't Exists!"
            raise forms.ValidationError(information)
        # if not request.user.is_authenticated:
        #     information = 'The Username is Registered. Please Register to Continue.'
        #     raise forms.ValidationError(information)
        return username_form


class RegistrationForm(forms.ModelForm):
    username = forms.CharField(min_length=8, max_length=20,
                               widget=forms.TextInput(attrs={
                                   'class': 'bg-gray-200 border-2 border-gray-100 focus:outline-none bg-gray-100 block w-full py-2 px-4 rounded-lg focus:border-gray-700',
                                   'placeholder': 'Enter your Username...',
                               }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'bg-gray-200 border-2 border-gray-100 focus:outline-none bg-gray-100 block w-full py-2 px-4 rounded-lg focus:border-gray-700',
        'placeholder': 'Enter your Email...'
    }))
    password1 = forms.CharField(min_length=8, max_length=20,
                                widget=forms.PasswordInput(attrs={
                                    'class': 'bg-gray-200 border-2 border-gray-100 focus:outline-none bg-gray-100 block w-full py-2 px-4 rounded-lg focus:border-gray-700',
                                    'placeholder': 'Enter a Password...'
                                }))
    password2 = forms.CharField(min_length=8, max_length=20,
                                widget=forms.PasswordInput(attrs={
                                    'class': 'bg-gray-200 border-2 border-gray-100 focus:outline-none bg-gray-100 block w-full py-2 px-4 rounded-lg focus:border-gray-700',
                                    'placeholder': 'Re-Enter your Password...',
                                }))

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )

    def clean_username(self):
        username_form = self.cleaned_data.get('username')
        obj = User.objects.all().filter(username__iexact=username_form)
        if obj.exists():
            information = 'The Username Already Exists!'
            raise forms.ValidationError(information)
        return username_form

    def clean_email(self):
        email_form = self.cleaned_data.get('email')
        obj = User.objects.all().filter(email=email_form)
        if obj.exists():
            information = 'The Email Already Exists!. Try Logging In.'
            raise forms.ValidationError(information)
        return email_form

    def clean_password2(self):
        password1_form = self.cleaned_data.get('password1')
        password2_form = self.cleaned_data.get('password2')
        if password1_form != password2_form:
            information = "The Passwords didn't Match!"
            raise forms.ValidationError(information)
        return password2_form


class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={
        'class': 'block w-full p-2 border rounded border-gray-300 focus:outline-none focus:ring-1 focus:ring-gray-400 focus:border-transparent',
        'placeholder': 'Enter you Registered Email ...',
        }))

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full px-5 py-1 text-gray-700 bg-gray-300 rounded focus:outline-none focus:bg-white',
        'placeholder': 'Enter your Old Password ...'
    }))
    new_password1 = forms.CharField(min_length=6, max_length=20,
                                    widget=forms.PasswordInput(
                                        attrs={
                                            'class': 'w-full px-5 py-1 text-gray-700 bg-gray-300 rounded focus:outline-none focus:bg-white',
                                            'placeholder': 'Enter your New Password ...'

                                        }))
    new_password2 = forms.CharField(min_length=6, max_length=20,
                                    widget=forms.PasswordInput(
                                        attrs={
                                            'class': 'w-full px-5 py-1 text-gray-700 bg-gray-300 rounded focus:outline-none focus:bg-white',
                                            'placeholder': 'Enter your New Password Again ...'

                                        }))

    class Meta:
        model = User,
        fields = (
            'old_password',
            'new_password1',
            'new_password2',
        )

class EditProfileForm(forms.ModelForm):
    user_image = forms.ImageField(label='Profile Image', required=False, widget=forms.FileInput(attrs={
        # 'placeholder': 'Add your Profile Image',
        'onchange': "loadFile(event)",
    }))
    user_banner = forms.ImageField(label='Banner Image', required=False, widget=forms.FileInput(
        attrs={
        'onchange': "loadFile_banner(event)",
    }
    ))
    bio = forms.CharField(label='Bio', widget=forms.Textarea(attrs={
        'placeholder': 'Enter an Awesome Bio ...',
        'rows': '2',
    }))
    instagram_url = forms.URLField(label='Insta Url', required=False, widget=forms.URLInput(attrs={
        'placeholder': 'Enter your Instagram url ...',
    }))
    linkedin_url = forms.URLField(label='Linkedin Url', required=False, widget=forms.URLInput(attrs={
        'placeholder': 'Enter your Linkedin url ...',
    }))
    github_url = forms.URLField(label='Github Url', required=False, widget=forms.URLInput(attrs={
        'placeholder': 'Enter your Github url ...',
    }))

    class Meta:
        model = Profile
        fields = (
            'user_image',
            'user_banner',
            'bio',
            'instagram_url',
            'linkedin_url',
            'github_url',
        )

    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'flex-1 py-2 border-b-2 border-gray-400 focus:border-green-400 text-gray-600 placeholder-gray-400 outline-none'

apps/web/apps/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.conf import settings
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import (
    LoginForm,
    RegistrationForm,
    UserPasswordChangeForm,
    EditProfileForm
)
from .models import Profile

# Create your views here.

User = get_user_model()


def login_view(request):
    if request.user.is_authenticated:
        return redirect('/')
    form = LoginForm(request.POST or None)
    if form.is_valid():
        remember_me = request.POST.get('rememberme', None)
        if remember_me is not None:
            request.session.set_expiry(settings.SESSION_COOKIE_AGE)
        username_data = form.cleaned_data.get('username')
        password_data = form.cleaned_data.get('password')
        user = authenticate(
            username=username_data,
            password=password_data
        )
        login(request=request, user=user)
        next_url = request.GET.get('next')
        if next_url:
            return redirect(next_url)
        return redirect('/')
    context = {
        'form': form,
    }
    return render(request, 'accounts/login_view.html', context=context)


def register_view(request):
    if request.user.is_authenticated:
        return redirect('/')
    form = RegistrationForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        new_password = form.cleaned_data.get('password2')
        user.set_password(raw_password=new_password)
        user.save()
        next_url = request.GET.get('next', None)
        if next_url:
            return redirect(next_url)
        return redirect('login')
    context = {
        'form': form,
    }
    return render(request, 'accounts/register_view.html', context=context)


@login_required
def logout_view(request):
    logout(request)
    return redirect('/')


class CustomPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'accounts/change_password/change_password.html'
    success_url = reverse_lazy('password_reset_complete')


class ProfileView(LoginRequiredMixin, View):
    template_name = 'accounts/profile/profile_view.html'

    def get(self, request, user, *args, **kwargs):
        instance = User.objects.filter(username=user)
        if not instance:
            return redirect('/error/')
        obj = Profile.objects.filter(user__username=user)
        if not obj.exists():
            created = Profile.objects.create(user=
                User.objects.get(username=user)
            )
        if request.user.username == user:
            is_user = True
        else:
            is_user = False
        context = {
            'user_context': instance.first(),
            'is_user': is_user,
        }
        return render(request, self.template_name, context=context)


class ProfileEditView(LoginRequiredMixin, View):
    template_name = 'accounts/profile/edit_profile.html'

    def get(self, request, *args, **kwargs):
        instance = Profile.objects.filter(user=request.user)
        if instance.exists():
            instance_pass = Profile.objects.get(user=request.user)
        else:
            instance_pass = Profile.objects.create(user=request.user)
        form = EditProfileForm(request.POST or None, instance=instance_pass)
        context = {
            'form': form,
        }
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        instance = Profile.objects.get(user=request.user)
        if not instance:
            return redirect('/error/')
        form = EditProfileForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('profile', request.user)
        context = {
            'form': form,
        }
        return render(request, self.template_name, context=context)

apps/templates/accounts/password_reset/password_reset.html
{% extends "base.html" %}

{% block title %} Reset Password {% endblock %}

{% block content %}

    <div class="flex min-h-screen bg-white">
        <div class="w-1/2 bg-cover md:block hidden"
             style="background-image:  url('https://images.unsplash.com/photo-1520243947988-b7b79f7873e9?ixid=MXwxMjA3fDB8MHxzZWFyY2h8NDd8fGJsYWNrJTIwZm9yZXN0fGVufDB8fDB8eWVsbG93&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60')">
        </div>
        <div class="md:w-1/2 max-w-lg mx-auto my-24 px-4 py-5 shadow-none">
            <div class="text-left p-0 font-sans">
                <h1 class=" text-gray-800 text-3xl font-medium">Forgot your password?</h1>
                <h3 class="p-1 text-gray-700">
                    Enter your email address below, and we'll email instructions for setting a new one.
                </h3>

            </div>
            <div class="mt-10">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <div class="mt-10">
                        <input type="submit" value="Send me the Instructions"
                               class="py-3 bg-green-500 text-white w-full rounded hover:bg-green-600">
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        document.getElementById('id_email').focus()
    </script>

{% endblock content %}

apps/templates/accounts/password_reset/password_reset_complete.html
{% extends "base.html" %}

{% block title %} Success {% endblock %}

{% block content %}

    <div class="grid w-full min-h-screen bg-gray-900 place-content-center">
        <div class="text-center">
            <p class="text-3xl font-bold text-gray-100 text center md:text-6xl">
                Your password has been Successfully Set.
            </p>
            <br><br>
            <p class="text-white text-lg">
                Use the New Password to Login.<br>
            </p>
            <br><br>
            <div style="padding: 10px;">
                <a href="{% url 'login' %}" class="py-2 px-2 font-medium text-white bg-green-500 rounded hover:bg-green-400 transition duration-300">
                    Sign In
                </a>
            </div>
        </div>
    </div>

{% endblock content %}

apps/templates/accounts/password_reset/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %} Change password {% endblock %}

{% block content %}

    <body class="bg-white font-family-karla h-screen">

    <div class="w-full flex flex-wrap">
        <div class="w-full md:w-1/2 flex flex-col">
            <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
                <p class="text-center text-3xl">Reset Your Password.</p>
                <form class="flex flex-col pt-3 md:pt-8" method="POST">{% csrf_token %}
                    {% for field in form %}
                        {% if field.errors %}
                            {% for err in field.errors %}
                                <center>
                                    <p class="text-red-500">{{ err }}</p>
                                </center>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}

                    <div class="flex flex-col pt-4">
                        <input type="password" id="id_new_password1" name="new_password1"
                               placeholder="Enter Your New Password"
                               class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">
                        <br>
                    </div>
                    <div class="flex flex-col pt-4">
                        <input type="password" id="id_new_password2" name="new_password2"
                               placeholder="Re Enter Your New Password"
                               class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">
                    </div>
                    <br>
                    <div class="text-center">
                        <label class="inline-flex items-center mt-3">
                            <input type="checkbox" id="show_reset" onclick="show_password_reset()"
                                   class="form-checkbox h-4 w-4 text-gray-600">
                            <span class="ml-2 text-gray-700">Show Password</span>
                        </label>
                    </div>
                    <input type="submit" value="Reset Password"
                           class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8">
                </form>
                <br><br>
                <div class="text-center">
                    <p>Already have an Account?
                        <a href="{% url 'login' %}" class="underline font-semibold">Login Here!</a>
                    </p>
                </div>
                <br>
                <div class="text-center">
                    <p>Don't have an account?
                        <a href="{% url 'register' %}" class="underline font-semibold">Register Here.</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="w-1/2 shadow-2xl">
            <img class="object-cover w-full h-screen hidden md:block" src="https://source.unsplash.com/IXUM4cJynP0">
        </div>
    </div>

    </body>

    <script>
        var password_reset_1 = document.getElementById('id_new_password1')
        var password_reset_2 = document.getElementById('id_new_password2')
        var show_password_reset_this = document.getElementById('show_reset')

        function show_password_reset() {
            if (show_password_reset_this.checked) {
                password_reset_1.type = 'text'
                password_reset_2.type = 'text'
            } else {
                password_reset_1.type = 'password'
                password_reset_2.type = 'password'
            }
        }
    </script>
{% endblock %}

apps/templates/accounts/password_reset/password_reset_done.html
{% extends "base.html" %}

{% block title %} Sent Email {% endblock %}

{% block content %}

    <div class="grid w-full min-h-screen bg-gray-900 place-content-center">
        <div class="text-center">
            <p class="text-3xl font-bold text-gray-100 text center md:text-6xl">
                Reset your Password
            </p>
            <br><br>
            <p class="text-white text-lg">
                An email has been sent with instructions to reset your Password.<br>
                Please Check it in the Spam/Promotions/Updates .
            </p>
        </div>
    </div>

{% endblock %}